package joelbits.model.ast.types;

public enum ExpressionType {
        ARRAYINDEX, ARRAYINIT, ASSIGN, ASSIGN_ADD, ASSIGN_DIV, ASSIGN_SUB,
        ASSIGN_MOD, CAST, CONDITIONAL, EQ, GT, GTEQ, LITERAL, LOGICAL_AND,
        LOGICAL_OR, LOGICAL_NOT, LT, LTEQ, NEQ, NEW, METHODCALL, NEWARRAY,
        OP_ADD, OP_SUB, OP_DEC, OP_DIV, OP_INC, OP_MOD, OP_MULT, OTHER,
        PARENTHESIS, TYPECOMPARE, VARIABLE_DECLARATION , VARIABLE_ACCESS
    }
